[misc]
disable = ["bun", "bun_packages", "pip3"]
display_time = false
assume_yes = true

[linux]
rpm_ostree = true

[firmware]
upgrade = true

[containers]
ignored_containers= ["quay.io/fedora/fedora-silverblue:latest"]
runtime = "podman"
