#!/bin/bash

set -euox pipefail


git clone https://github.com/flatpak/flatpak
cd flatpak
dnf -y builddep flatpak
dnf -y install gettext-devel socat
git submodule update --init
meson setup --prefix=/usr --sysconfdir=/etc --localstatedir=/var -Dinstalled_tests=true -Dselinux_module=enabled -Dsystem_bubblewrap=bwrap -Dsystem_dbus_proxy=xdg-dbus-proxy _build
meson compile -C _build
meson install -C _build

rm /usr/bin/flatpak 

mv _build/app/flatpak /usr/bin


flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak override --filesystem=xdg-config/gtk-3.0:rw
flatpak override --filesystem=xdg-config/gtk-4.0:rw

rsync -rvK /ctx/system_files/shared/ /
ln -s /run /var/run

python3 /ctx/update_os_release.py
echo "skllyblue" >> /etc/hostname

dconf update
