#!/bin/bash

set -euxo pipefail

uneeded_apps=("syncthing-start syncthing-ui yelp")


dnf5 install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

dnf5 config-manager setopt fedora-cisco-openh264.enabled=1
for pkg in kernel kernel-core kernel-modules kernel-modules-core; do
  rpm --erase $pkg --nodeps
done

pushd /usr/lib/kernel/install.d
printf '%s\n' '#!/bin/sh' 'exit 0' > 05-rpmostree.install
printf '%s\n' '#!/bin/sh' 'exit 0' > 50-dracut.install
chmod +x  05-rpmostree.install 50-dracut.install
popd

dnf -y copr enable bieszczaders/kernel-cachyos-lto
dnf -y copr disable bieszczaders/kernel-cachyos-lto
dnf -y --enablerepo copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-lto install \
  kernel-cachyos-lto

dnf -y copr enable bieszczaders/kernel-cachyos-addons
dnf -y copr disable bieszczaders/kernel-cachyos-addons
dnf -y --enablerepo copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons swap zram-generator-defaults cachyos-settings
dnf -y --enablerepo copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons install \
  scx-scheds-git \
  scx-manager

dnf5 install -y @development-tools \
    webkit2gtk4.1-devel \
    waydroid \
    alsa-firmware \
    mutter-devel \
    openssl \
    fzf \
    codium \
    steam \
    godot \
    gamescope \
    tailscale \
    distrobox \
    syncthing \
    just \
    fastfetch \
    vim \
    nautilus-python \
    clapper 

dnf5 remove -y firefox \
    toolbox \
    blender \
    gnome-shell-extension-background-logo \
    gnome-shell-extension-window-list \
    gnome-shell-extension-apps-menu \
    gnome-shell-extension-launch-new-instance \
    gnome-shell-extension-places-menu \
    gnome-software

dnf5 -y copr enable lilay/topgrade
dnf5 -y install topgrade
dnf5 -y copr disable lilay/topgrade

dnf5 -y copr enable vdanielmo/git-credential-manager 
dnf5 -y install git-credential-manager
dnf5 -y copr disable vdanielmo/git-credential-manager

dnf5 -y copr enable umutd3401/extension-manager
dnf5 -y install extension-manager
dnf5 -y copr disable umutd3401/extension-manager

# dnf5 -y copr enable bieszczaders/kernel-cachyos
# dnf5 -y install kernel-cachyos kernel-cachyos-devel-matched
# dnf5 -y copr disable bieszczaders/kernel-cachyos

for f in $uneeded_apps; do
    rm -f /usr/share/applications/$f.desktop
done

dnf5 -y autoremove

systemctl enable podman.socket
systemctl enable tailscaled
systemctl enable sshd
# systemctl enable bazaar
