#!/bin/bash

set -euxo pipefail

# regenerate initramfs - stolen from ublue-os/main
KERNEL_VERSION="$(find "/usr/lib/modules" -maxdepth 1 -type d ! -path "/usr/lib/modules" -exec basename '{}' ';' | sort | tail -n 1)"

# Ensure Initramfs is generated
export DRACUT_NO_XATTR=1
dracut --no-hostonly --kver "$KERNEL_VERSION" --reproducible --zstd -v --add ostree -f "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"
chmod 0600 "/lib/modules/${KERNEL_VERSION}/initramfs.img"